config/routes.rb
Ayadu::Application.routes.draw do

    get "about" => "pages#about"

  resources :orders

  get "profiles/show"
  resources :pins
  root "pins#index"

  get '/:id', to: 'profiles#show'

  devise_for :users

  get '/request/:pin_id' => "orders#new_request_for_pin"

end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/models/pin.rb
class Pin < ActiveRecord::Base
belongs_to :user
has_attached_file :image, :styles => { :large => "500x500>", :medium => "300x300>", :thumb => "100x100>" }



validates :title, presence: true
validates :description, presence: true
validates :image, presence: true
validates :daily, numericality: true
validates :weekly, numericality: true
validates :monthly, numericality: true
validates :advance, numericality: true




end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  validates :name, presence: true
  validates :mobile, numericality: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :country, presence: true
  validates :pincode, numericality: true, allow_nil: true





  has_many :pins

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 # Prevent CSRF attacks by raising an exception.
 # For APIs, you may want to use :null_session instead.
 protect_from_forgery with: :exception
 before_filter :configure_permitted_parameters, if: :devise_controller?

protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :mobile, :address, :city, :state, :country, :pincode) }
   devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :mobile, :address, :city, :state, :country, :pincode, :password, :current_password) }
 end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :check_for_admin, except:[:new_request_for_pin, :create]

  # GET /orders
  # GET /orders.json

  def new_request_for_pin
    @pin = Pin.find(request[:pin_id]) #request using url
    @order = Order.new



  end
  

  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to '/', notice: 'Order was successfully created.' }


        format.json { render action: 'show', status: :created, location: @order }
      else
        format.html { render action: 'new' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:pin_id, :customer_email, :customer_name, :message, :customer_mobile)
    end

    def check_for_admin
      if current_user.email != "ud@thetraces.com" 
        redirect_to '/'
      end

    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]



  # GET /pins
  # GET /pins.json
 def index
   @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 30)
 end
  

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.build
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.build(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pin }
      else
        format.html { render action: 'new' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id]) 
      #@pin = Pin.find(params(id: params[:id])
    end



    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end

      # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:title, :description, :image, :daily, :weekly, :monthly, :advance)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
  	@user = User.find_by_name(params[:id])

  	if @user

  	    	@pins = @user.pins.all

  		render action: :show
  	else

  		render file: 'public/404', status: 404, formats:[:html]

  	end
  end






 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
<div class="container">


  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Ayadu", root_path, class: "navbar-brand"%>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <% if user_signed_in? %>
        
        <li>
            <%= link_to new_pin_path do %>
              <span class="glyphicon glyphicon-plus"></span> New Pin
            <% end %>
          </li>

          <li><%= link_to "Account Settings", edit_user_registration_path %></li>

          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</div> <!-- container ends -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ayadu</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <%= render 'layouts/header' %>



	<div class="container">
	
		<% flash.each do |name, msg| %>
     	<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
		
		<%= yield %>
	
	</div>

</body>
</html>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <thead>
    <tr>
      <th>Pin</th>
      <th>Customer email</th>
      <th>Customer name</th>
      <th>Message</th>
      <th>Customer mobile</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.pin_id %></td>
        <td><%= order.customer_email %></td>
        <td><%= order.customer_name %></td>
        <td><%= order.message %></td>
        <td><%= order.customer_mobile %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/new_request_for_pin.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :pin_id, :value => @pin.id %>
  </div>
  <div class="field">
    <%= f.label :customer_email %><br>
    <%= f.text_field :customer_email %>
  </div>
  <div class="field">
    <%= f.label :customer_name %><br>
    <%= f.text_field :customer_name %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </div>
  <div class="field">
    <%= f.label :customer_mobile %><br>
    <%= f.text_field :customer_mobile %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pin:</strong>
  <%= @order.pin_id %>
</p>

<p>
  <strong>Customer email:</strong>
  <%= @order.customer_email %>
</p>

<p>
  <strong>Customer name:</strong>
  <%= @order.customer_name %>
</p>

<p>
  <strong>Message:</strong>
  <%= @order.message %>
</p>

<p>
  <strong>Customer mobile:</strong>
  <%= @order.customer_mobile %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/pages/_home.html.erb
<div class="jumbotron center">
  <h1>A simple way to rent stuff online</h1>
  <h4>We are creating an open market place where you will able to list your stuff for rent and also rent stuff from other awesome people</h4>
  <p>
    <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
    <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
  </p>

</div>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>The idea for Ayadu came about when we looked at the stuff lying around in our flat which we dint use on a regular basis </p>
<p>Love to hear from you guys! send email to <h3>ud@thetraces.com</h3></p>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

      <div class="form-group">
        <%= f.label :daily %>
        <%= f.phone_field :daily, class: "form-control" %>
      </div>

     <div class="form-group">
        <%= f.label :weekly %>
        <%= f.phone_field :weekly, class: "form-control" %>
      </div>

     <div class="form-group">
        <%= f.label :monthly %>
        <%= f.phone_field :monthly, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :advance %>
        <%= f.phone_field :advance, class: "form-control" %>
      </div>



  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>





<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(pin.image.url(:medium)), pin %>
      <div class="panel-body">
        <h4><%= pin.title %></h4>
        <%= truncate  pin.description, length: 20 %><br/>
        Daily Rs:<%= pin.daily %><br/>
        Weekly Rs:<%= pin.weekly %><br/>
        Monthly Rs:<%= pin.monthly %><br/>
        

        <strong><%= link_to pin.user.name, pin.user.name %></strong>
        <% if pin.user == current_user %>
          <div class="actions">
             <%= link_to edit_pin_path(pin) do %>
              <span class="glyphicon glyphicon-edit"></span>
              Edit
            <% end %>
            
             <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash"></span>
              Delete
            <% end %>

          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div class="center">
   <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<%= link_to 'Back', pins_path %>

<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading center">
        <%= image_tag @pin.image.url(:large) %>
      </div>
      <div class="panel-body">
      	<h3><%= @pin.title %></h3>
        <p><%= @pin.description %></p>

        Daily Rs:<%= @pin.daily %><br/>
        Weekly Rs:<%= @pin.weekly %><br/>
        Monthly Rs:<%= @pin.monthly %><br/>
        Advance Rs:<%= @pin.advance %><br/>

        

        <p><strong><%= link_to @pin.user.name, "/#{@pin.user.name}"  %></strong></p>
        <a href="/request/<%=@pin.id%>">Request Info</a>

        <% if @pin.user == current_user %>
         <%= link_to edit_pin_path(@pin) do %>
        <span class="glyphicon glyphicon-edit"></span>
        Edit
      <% end %>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<h1><%= @user.name + "'s stuff available for rent" %></h1>
<h4>Location: <%=@user.city%></h4>

<% if @pins %>
<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(pin.image.url(:medium)), pin %>
      <div class="panel-body">
        <h4><%= pin.title %></h4>
                <h5>Location: <strong><%=pin.user.city%></strong></h5>

        Daily Rs:<%= pin.daily %><br/>
        Weekly Rs:<%= pin.weekly %><br/>
        Monthly Rs:<%= pin.monthly %><br/>
       <%= truncate  pin.description, length: 20 %><br/>

        

        <strong><%= link_to pin.user.name, pin.user.name  %></strong>
        <% if pin.user == current_user %>
          <div class="actions">
             <%= link_to edit_pin_path(pin) do %>
              <span class="glyphicon glyphicon-edit"></span>
              Edit
            <% end %>
            
             <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash"></span>
              Delete
            <% end %>

          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<%end%>